version: '3'
services:
  frontend:
    build:
      context: ./Front
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
  backend:
    build:
      context: ./Back
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - GITHUB_OAUTH_CLIENT_ID
      - GITHUB_OAUTH_CLIENT_SECRET
      - OPENAI_API_KEY
